=== VigoTech/vigotech.github.io/static/vigotech-schema.json
{
  "title": "VigoTech Alliance members JSON schema",
  "type": "object",
  "description": "",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "required": [
    "name",
    "logo"
  ],
  "properties": {
    "name": {
      "type": "string",
      "description": "Alliance name"
    },
    "logo": {
      "type": "string",
      "description": "Logo url"
    },
    "sticker": {
      "type": "string",
      "description": "Sticker image url"
    },
    "links": {
      "type": "object",
      "description": "Alliance site and social links",
      "items": {
        "type": "object",
        "description": "Link",
        "required": [
          "key",
          "url"
        ],
        "properties": {
          "key": {
            "type": "string",
            "description": "Link key (used to show icon)"
          },
          "url": {
            "type": "string",
            "description": "Link url"
          }
        }
      }
    },
    "events": {
      "type": [
        "object",
        "array"
      ],
      "description": "Events data source",
      "items": {
        "type": "object",
        "description": "Event data source",
        "required": [
          "type"
        ],
        "properties": {
          "type": {
            "type": "string",
            "description": "Data source type allowed values (meetup, eventbrite, json)"
          },
          "meetupid": {
            "type": "string",
            "description": "Meetup id"
          },
          "eventbriteid": {
            "type": "string",
            "description": "Eventbrite id"
          },
          "source": {
            "type": "string",
            "description": "Source URL"
          }
        }
      }
    },
    "members": {
      "type": ["array", "object"],
      "description": "Alliance members",
      "items": {
        "type": "object",
        "description": "Member",
        "required": [
          "key",
          "name",
          "logo"
        ],
        "properties": {
          "key": {
            "type": "string",
            "description": "Member unique id"
          },
          "name": {
            "type": "string",
            "description": "Alliance name"
          },
          "logo": {
            "type": "string",
            "description": "Logo url"
          },
          "sticker": {
            "type": "string",
            "description": "Sticker image url"
          },
          "links": {
            "type": "object",
            "description": "Alliance site and social links",
            "items": {
              "type": "object",
              "description": "Link",
              "required": [
                "key",
                "url"
              ],
              "properties": {
                "key": {
                  "type": "string",
                  "description": "Link key (used to show icon)"
                },
                "url": {
                  "type": "string",
                  "description": "Link url"
                }
              }
            }
          },
          "events": {
            "type": ["object", "array"],
            "description": "Events data source",
            "items": {
              "type": "object",
              "description": "Event data source",
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "type": "string",
                  "description": "Data source type allowed values (meetup, eventbrite, json)"
                },
                "meetupid": {
                  "type": "string",
                  "description": "Meetup id"
                },
                "eventbriteid": {
                  "type": "string",
                  "description": "Eventbrite id"
                },
                "source": {
                  "type": "string",
                  "description": "Source URL"
                }
              }
            }
          },
          "videos": {
            "type": "array",
            "description": "Member videos source",
            "items": {
              "type": "object",
              "description": "Member video source",
              "required": [
                "type"
              ],
              "properties": {
                "type": {
                  "type": "string",
                  "description": "Video source tyoe"
                },
                "source": {
                  "type": "string",
                  "description": "Telteck videos feed"
                },
                "channel_id": {
                  "type": "string",
                  "description": "Youtube channel id (not channel name)"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== VigoTech/vigotech.github.io/static/vigotech.json
{
  "name": "VigoTech Alliance",
  "logo": "https://github.com/VigoTech/Design-elements/blob/master/01%20IDENTIDAD%20CORPORATIVA/01%20EXPORT/PNG/Logo%20VIGOTECH_avatar_redondo.png?raw=true",
  "sticker": "http://hexb.in/hexagons/vigotech.png",
  "links": {
    "web": "https://vigotech.org/",
    "twitter": "http://twitter.com/vigotechallianc",
    "mail": "alliance@vigotech.org",
    "github": "https://github.com/VigoTech"
  },
  "events": {
    "type": "eventbrite",
    "eventbriteid": "17365087639"
  },
  "members": {
    "agilevigo": {
      "name": "Agile Vigo",
      "logo": "https://vigotech.org/images/agile_vigo.jpg",
      "links": {
        "twitter": "https://twitter.com/agilevigo",
        "meetup": "https://www.meetup.com/es-ES/agile-vigo/",
        "github": "https://github.com/agileVigo"
      },
      "events": [
        {
          "type": "meetup",
          "meetupid": "agile-vigo"
        }
      ]
    },
    "aindustriosa": {
      "name": "A Industriosa",
      "logo": "https://vigotech.org/images/aindustriosa.png",
      "links": {
        "web": "https://aindustriosa.org/",
        "twitter": "https://twitter.com/aindustriosa",
        "meetup": "https://www.meetup.com/es-ES/AIndustriosa/",
        "youtube": "https://www.youtube.com/channel/UC9DPKfcLiNd7SEU-QLlIG7A"
      },
      "events": {
        "type": "meetup",
        "meetupid": "AIndustriosa"
      },
      "videos": [
        {
          "type": "youtube",
          "channel_id": "UC9DPKfcLiNd7SEU-QLlIG7A"
        }
      ]
    },
    "blockchaingal": {
      "name": "Blockchain.gal Vigo",
      "logo": "https://vigotech.org/images/blockchaingal.png",
      "links": {
        "web": "https://blockchain.gal/",
        "twitter": "https://twitter.com/blockchain_gal",
        "meetup": "https://www.meetup.com/es-ES/blockchain_gal_vigo/",
        "github": "https://github.com/blockchain-gal"
      },
      "events": {
        "type": "meetup",
        "meetupid": "blockchain_gal_vigo"
      }
    },
    "craftersvigo": {
      "name": "Crafters Vigo",
      "logo": "https://vigotech.org/images/craftersVigo.png",
      "links": {
        "twitter": "https://twitter.com/CraftersVigo",
        "meetup": "https://www.meetup.com/craftersvigo/"
      },
      "events": {
        "type": "meetup",
        "meetupid": "craftersvigo"
      }
    },
    "galpon": {
      "name": "GALPon",
      "logo": "https://vigotech.org/images/galpon.png",
      "links": {
        "web": "https://www.galpon.org",
        "maillist": "https://www.galpon.org/content/listas-correo-galpon"
      },
      "events": {
        "type": "json",
        "source": "https://raw.githubusercontent.com/Daniel-at-github/vigotech_events/refs/heads/main/calendars/obradoiros_galpon.json"
      }
    },
    "galstech": {
      "name": "GalsTech",
      "logo": "https://vigotech.org/images/galstech.png",
      "links": {
        "meetup": "https://www.meetup.com/GalsTech/",
        "twitter": "https://twitter.com/galstech_?lang=es"
      },
      "events": {
        "type": "meetup",
        "meetupid": "galstech"
      }
    },
    "gdgvigo": {
      "name": "GDG Vigo",
      "logo": "https://vigotech.org/images/gdg_vigo.png",
      "links": {
        "twitter": "http://twitter.com/GDGVigo/",
        "meetup": "https://www.meetup.com/es-ES/GDGVigo/?chapter_analytics_code=UA-73757047-1",
        "youtube": "https://www.youtube.com/user/GDGVigo"
      },
      "events": [
        {
          "type": "meetup",
          "meetupid": "GDGVigo"
        }
      ],
      "videos": [
        {
          "type": "youtube",
          "channel_id": "UC3BXzHGAMx7tAgVD1CqCuCQ"
        }
      ]
    },
    "joomlavigo": {
      "name": "Grupo de Usuarios de Joomla de Vigo",
      "logo": "https://vigotech.org/images/joomla_vigo.png",
      "links": {
        "web": "https://www.joomlavigo.es/",
        "twitter": "https://twitter.com/JoomlaVigo",
        "facebook": "https://www.facebook.com/JoomlaVigo/"
      }
    },
    "phpvigo": {
      "name": "PHPVigo",
      "logo": "https://vigotech.org/images/php_vigo.jpg",
      "links": {
        "web": "http://phpvigo.com/",
        "meetup": "https://www.meetup.com/es-ES/PHPVigo/",
        "twitter": "https://twitter.com/phpvigo",
        "github": "https://github.com/phpvigo",
        "youtube": "https://www.youtube.com/c/phpvigo"
      },
      "events": [
        {
          "type": "meetup",
          "meetupid": "phpvigo"
        },
        {
          "type": "json",
          "source": "https://www.phpvigo.com/events.json"
        }
      ],
      "videos": [
        {
          "type": "youtube",
          "channel_id": "UCzcSOwRc7bfKs9jPehJRNxQ"
        }
      ]
    },
    "pythonvigo": {
      "name": "PythonVigo",
      "logo": "https://vigotech.org/images/python_vigo.png",
      "links": {
        "web": "https://www.python-vigo.es/",
        "twitter": "https://twitter.com/python_vigo",
        "maillist": "https://lists.es.python.org/listinfo/vigo",
        "youtube": "https://www.youtube.com/channel/UCTUXabChakosnupWEnz4xTA"
      },
      "events": {
        "type": "json",
        "source": "https://www.python-vigo.es/events.json"
      },
      "videos": [
        {
          "type": "youtube",
          "channel_id": "UCTUXabChakosnupWEnz4xTA"
        }
      ]
    },
    "seogalicia": {
      "name": "Seo Galicia",
      "logo": "https://vigotech.org/images/seogalicia.png",
      "links": {
        "facebook": "https://www.facebook.com/SEOGaliciaMeetup",
        "meetup": "https://www.meetup.com/es/SEO-Galicia/",
        "twitter": "https://twitter.com/seo_galicia"
      },
      "events": {
        "type": "meetup",
        "meetupid": "SEO-Galicia"
      }
    },
    "sysadmingalicia": {
      "name": "SysAdmin Galicia",
      "logo": "https://vigotech.org/images/sysadmin_galicia.jpg",
      "links": {
        "meetup": "https://www.meetup.com/es-ES/Sysadmin-Galicia/",
        "twitter": "https://twitter.com/sysadmingalicia/"
      },
      "events": {
        "type": "meetup",
        "meetupid": "Sysadmin-Galicia"
      },
      "videos": [
        {
          "type": "teltek",
          "source": "https://replay.teltek.es/podcast/series/58af67c7a7bc283f008b456c/collection.xml"
        }
      ]

    },
    "uxgalicia": {
      "name": "UX Galicia",
      "logo": "https://vigotech.org/images/ux_gal.jpg",
      "links": {
        "web": "http://www.uxgalicia.com/",
        "meetup": "https://www.meetup.com/es-ES/Experiencia-de-Usuario-Meetup/",
        "twitter": "https://twitter.com/uxgalicia/"
      },
      "events": {
        "type": "meetup",
        "meetupid": "Experiencia-de-Usuario-Meetup"
      }
    },
    "vigoadg": {
      "name": "Vigo Android Developer Group",
      "logo": "https://vigotech.org/images/vigoadg.jpg",
      "links": {
        "twitter": "https://twitter.com/VigoADG",
        "meetup": "https://www.meetup.com/Vigo-Android-Developer-Group/"
      },
      "events": {
        "type": "meetup",
        "meetupid": "Vigo-Android-Developer-Group"
      }
    },
    "vigojug": {
      "name": "VigoJUG",
      "logo": "https://vigotech.org/images/vigojug.jpg",
      "links": {
        "web": "http://www.vigojug.org/",
        "github": "https://github.com/vigojug/",
        "meetup": "https://www.meetup.com/es-ES/Vigo-JUG/",
        "twitter": "https://twitter.com/vigojug/",
        "linkedin": "https://www.linkedin.com/organization/11056204",
        "youtube": "https://www.youtube.com/channel/UCYSy-eQm6Q02o7WiR6JTqJg",
        "ivoox": "https://www.ivoox.com/podcast-laretasgeek_sq_f1939875_1.html",
        "spotify": "https://open.spotify.com/show/2iMpr5Kos3j5YuqB6HfYWL"
      },
      "events": {
        "type": "meetup",
        "meetupid": "Vigo-JUG"
      },
      "videos": [
        {
          "type": "youtube",
          "channel_id": "UCNOihTnorv6dZDANaPXgx_g"
        },
        {
          "type": "youtube",
          "channel_id": "UCYSy-eQm6Q02o7WiR6JTqJg"
        }
      ]
    },
    "wppontevedra": {
      "name": "WordpressPontevedra",
      "logo": "https://vigotech.org/images/wordpress-pontevedra.png",
      "links": {
        "meetup": "https://www.meetup.com/es-ES/Pontevedra-WordPress-Meetup/",
        "twitter": "https://twitter.com/wppontevedra"
      },
      "events": {
        "type": "meetup",
        "meetupid": "Pontevedra-WordPress-Meetup"
      }
    },
    "vigowordpress": {
      "name": "VigoWordpress",
      "logo": "https://vigotech.org/images/vigowordpress.png",
      "links": {
        "mail": "wpmeetupvigo@gmail.com",
        "meetup": "https://www.meetup.com/es-ES/Vigo-WordPress-Meetup/",
        "twitter": "https://twitter.com/wp_vigo",
        "youtube": "https://www.youtube.com/channel/UCuipENHgKAhr1VgK59156Tw"
      },
      "events": {
        "type": "meetup",
        "meetupid": "Vigo-WordPress-Meetup"
      },
      "videos": [
        {
          "type": "youtube",
          "channel_id": "UCuipENHgKAhr1VgK59156Tw"
        }
      ]
    }
  }
}

=== VigoTech/vigotech.github.io/vigotech.json
{
  "name": "VigoTech Alliance",
  "logo": "https://github.com/VigoTech/Design-elements/blob/master/01%20IDENTIDAD%20CORPORATIVA/01%20EXPORT/PNG/Logo%20VIGOTECH_claim-es-horizontal-fondo-blanco.png?raw=true",
  "sticker": "http://hexb.in/hexagons/vigotech.png",
  "links": {
    "web": "http://vigotech.org/",
    "twitter": "http://twitter.com/vigotechallianc",
    "mail": "alliance@vigotech.org",
    "github": "https://github.com/VigoTech"
  },
  "members": {
    "agilevigo": {
      "name": "Agile Vigo",
      "logo": "http://vigotech.org/images/agile_vigo.jpg",
      "links": {
        "web": "https://www.agilevigo.com/",
        "twitter": "https://twitter.com/agilevigo",
        "meetup": "https://www.meetup.com/es-ES/agile-vigo/",
        "github": "https://github.com/agileVigo"
      }
    },
    "aindustriosa": {
      "name": "Agile Vigo",
      "logo": "http://vigotech.org/images/aindustriosa.png",
      "links": {
        "web": "https://aindustriosa.org/",
        "twitter": "https://twitter.com/aindustriosa",
        "meetup": "https://www.meetup.com/es-ES/AIndustriosa/",
        "youtube": "https://www.youtube.com/channel/UC9DPKfcLiNd7SEU-QLlIG7A"
      }
    },
    "blockchaingal": {
      "name": "Blockchain.gal Vigo",
      "logo": "http://vigotech.org/images/blockchaingal.png",
      "links": {
        "web": "https://blockchain.gal",
        "twitter": "https://twitter.com/blockchain_gal",
        "meetup": "https://www.meetup.com/es-ES/blockchain_gal_vigo",
        "github": "https://github.com/blockchain-gal"
      }
    },
    "codesign": {
      "name": "CodeSign Project",
      "logo": "http://vigotech.org/images/codesign.png",
      "links": {
        "facebook": "https://www.facebook.com/codesignproj/",
        "twitter": "https://twitter.com/codesign_pro/",
        "meetup": "https://www.meetup.com/es-ES/codesign-project/",
        "linkedin": "https://www.linkedin.com/company-beta/11049865/"
      }
    },
    "galpon": {
      "name": "GALPon",
      "logo": "http://vigotech.org/images/galpon.png",
      "links": {
        "web": "https://www.galpon.org",
        "twitter": "https://twitter.com/galpon",
        "maillist": "https://www.galpon.org/content/listas-correo-galpon"
      }
    },
    "galstech": {
      "name": "GalsTech",
      "logo": "http://vigotech.org/images/galstech.png",
      "links": {
        "meetup": "https://www.meetup.com/GalsTech/",
        "twitter": "https://twitter.com/galstech_?lang=es"
      }
    },
    "gdgvigo": {
      "name": "GDG Vigo",
      "logo": "http://vigotech.org/images/gdg_vigo.png",
      "links": {
        "twitter": "http://twitter.com/GDGVigo/",
        "meetup": "https://www.meetup.com/es-ES/GDGVigo/?chapter_analytics_code=UA-73757047-1",
        "youtube": "https://www.youtube.com/user/GDGVigo"
      }
    },
    "joomlavigo": {
      "name": "Grupo de Usuarios de Joomla de Vigo",
      "logo": "http://vigotech.org/images/joomla_vigo.png",
      "links": {
        "web": "https://www.joomlavigo.es/",
        "twitter": "https://twitter.com/JoomlaVigo",
        "facebook": "https://www.facebook.com/JoomlaVigo/",
        "meetup": "https://www.meetup.com/es-ES/Grupo-de-Usuarios-de-Joomla-de-Vigo/"
      }
    },
    "jsvigo": {
      "name": "JavascriptVigo",
      "logo": "http://vigotech.org/images/jsvigo.png",
      "links": {
        "meetup": "https://www.meetup.com/es-ES/JavaScriptVigo/",
        "twitter": "http://twitter.com/JavaScriptVigo/",
        "youtube": "https://www.youtube.com/channel/UCjFplxtEs0XtunTn-n0LUtQ"
      }
    },
    "phpvigo": {
      "name": "PHPVigo",
      "logo": "http://vigotech.org/images/php_vigo.jpg",
      "links": {
        "web": "http://phpvigo.com/",
        "meetup": "https://www.meetup.com/es-ES/PHPVigo/",
        "twitter": "https://twitter.com/phpvigo",
        "github": "https://github.com/phpvigo",
        "youtube": "https://www.youtube.com/c/phpvigo"
      }
    },
    "pythonvigo": {
      "name": "PythonVigo",
      "logo": "http://vigotech.org/images/python_vigo.png",
      "links": {
        "web": "https://www.python-vigo.es/",
        "twitter": "https://twitter.com/python_vigo?lang=es",
        "maillist": "https://lists.es.python.org/listinfo/vigo",
        "youtube": "https://www.youtube.com/channel/UCTUXabChakosnupWEnz4xTA"
      }
    },
    "seogalicia": {
      "name": "Seo Galicia",
      "logo": "http://vigotech.org/images/seogalicia.png",
      "links": {
        "facebook": "https://www.facebook.com/SEOGaliciaMeetup",
        "meetup": "https://www.meetup.com/es/SEO-Galicia/",
        "twitter": "https://twitter.com/seo_galicia"
      }
    },
    "sysadmingalicia": {
      "name": "SysAdmin Galicia",
      "logo": "http://vigotech.org/images/sysadmin_galicia.jpg",
      "links": {
        "meetup": "https://www.meetup.com/es-ES/Sysadmin-Galicia/",
        "twitter": "https://twitter.com/sysadmingalicia/"
      }
    },
    "uxgalicia": {
      "name": "UX Galicia",
      "logo": "http://vigotech.org/images/ux_gal.jpg",
      "links": {
        "web": "http://www.uxgalicia.com/",
        "meetup": "https://www.meetup.com/es-ES/Experiencia-de-Usuario-Meetup/",
        "twitter": "https://twitter.com/uxgalicia/"
      }
    },
    "vigoadg": {
      "name": "Vigo Android Developer Group",
      "logo": "http://vigotech.org/images/vigoadg.png",
      "links": {
        "twitter": "https://twitter.com/VigoADG",
        "meetup": "https://www.meetup.com/Vigo-Android-Developer-Group/"
      }
    },
    "vigobrain": {
      "name": "Vigo Brain",
      "logo": "http://vigotech.org/images/vigobrain.png",
      "links": {
        "github": "https://github.com/vigobrain/",
        "meetup": "https://www.meetup.com/es-ES/VigoBrain/",
        "twitter": "https://twitter.com/vigobrain/"
      }
    },
    "vigojug": {
      "name": "VigoJUG",
      "logo": "http://vigotech.org/images/vigojug.jpg",
      "links": {
        "web": "http://www.vigojug.org/",
        "github": "https://github.com/vigojug/",
        "meetup": "https://www.meetup.com/es-ES/Vigo-JUG/",
        "twitter": "https://twitter.com/vigojug/",
        "linkedin": "https://www.linkedin.com/organization/11056204",
        "youtube": "https://www.youtube.com/channel/UCNOihTnorv6dZDANaPXgx_g"
      }
    },
    "wppontevedra": {
      "name": "WordpressPontevedra",
      "logo": "http://vigotech.org/images/wordpress-pontevedra.png",
      "links": {
        "meetup": "https://www.meetup.com/es-ES/Pontevedra-WordPress-Meetup/",
        "twitter": "https://twitter.com/wppontevedra"
      }
    },
    "vigowordpress": {
      "name": "VigoWordpress",
      "logo": "http://vigotech.org/images/vigowordpress.png",
      "links": {
        "mail": "wpmeetupvigo@gmail.com",
        "meetup": "https://www.meetup.com/es-ES/Vigo-WordPress-Meetup/",
        "twitter": "https://twitter.com/wp_vigo",
        "youtube": "https://www.youtube.com/channel/UCuipENHgKAhr1VgK59156Tw"
      }
    }
  }
}
